---
- name: Install tree package
  hosts: all
  become: true
  tasks:
  - name: To install tree package
    yum:
      name: tree
      state: present

  - name: To install git package
    yum:
      name: git
      state: present

  - name: To install httpd package
    yum:
      name: httpd
      state: present
